/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goblinherowar.Frame;

/**
 *
 * @author peeravich.c
 */
public class Home extends javax.swing.JPanel{

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        homeStart.setOpaque(false);
        homeStart.setContentAreaFilled(false);
        homeStart.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeStart = new javax.swing.JButton();
        HomeBG = new javax.swing.JLabel();

        setLayout(null);

        homeStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/home_start.png"))); // NOI18N
        homeStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeStartMouseClicked(evt);
            }
        });
        add(homeStart);
        homeStart.setBounds(350, 440, 260, 65);

        HomeBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/Home.jpg"))); // NOI18N
        HomeBG.setText("jLabel1");
        HomeBG.setMaximumSize(new java.awt.Dimension(960, 540));
        HomeBG.setMinimumSize(new java.awt.Dimension(960, 540));
        HomeBG.setPreferredSize(new java.awt.Dimension(960, 540));
        HomeBG.setSize(new java.awt.Dimension(960, 540));
        add(HomeBG);
        HomeBG.setBounds(0, 0, 960, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void homeStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeStartMouseClicked
        Home.super.setVisible(false);
        new JFrame().add(new Scene1());
        new Scene1().setVisible(true);
    }//GEN-LAST:event_homeStartMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HomeBG;
    private javax.swing.JButton homeStart;
    // End of variables declaration//GEN-END:variables
}
