/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goblinherowar.Frame;

import goblinherowar.API.SceneManager;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author peeravich.c
 */
public class Home extends Scene{
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        homeStart.setOpaque(false);
        homeStart.setContentAreaFilled(false);
        homeStart.setBorderPainted(false);
    }
    
    public ArrayList<JButton> getButton(){
        ArrayList<JButton> j = new ArrayList<>();
        j.add(homeStart);
        return j;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeStart = new javax.swing.JButton();
        HomeBG = new javax.swing.JLabel();

        setLayout(null);

        homeStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/homeComponent/home_start.png"))); // NOI18N
        homeStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeStartActionPerformed(evt);
            }
        });
        add(homeStart);
        homeStart.setBounds(350, 440, 260, 59);

        HomeBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/homeComponent/Home.jpg"))); // NOI18N
        HomeBG.setLabelFor(HomeBG);
        HomeBG.setText("jLabel1");
        HomeBG.setMaximumSize(new java.awt.Dimension(960, 540));
        HomeBG.setMinimumSize(new java.awt.Dimension(960, 540));
        HomeBG.setPreferredSize(new java.awt.Dimension(960, 540));
        HomeBG.setSize(new java.awt.Dimension(960, 540));
        add(HomeBG);
        HomeBG.setBounds(0, 0, 960, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void homeStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeStartActionPerformed
        // TODO add your handling code here:
        MainFrame.setSceneVisible(0, false);
        MainFrame.addScene(1,0);     //SceneManager.randomScene()
        MainFrame.setSceneVisible(1, true);    //SceneManager.randomScene()
        MainFrame.setKeyButtonEnabled(true);
        MainFrame.setTransparent(1);    //SceneManager.randomScene()
        
    }//GEN-LAST:event_homeStartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HomeBG;
    private javax.swing.JButton homeStart;
    // End of variables declaration//GEN-END:variables
}
