/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package goblinherowar.Frame;

import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author spyspoisspui
 */
public class MainFrame extends javax.swing.JFrame{
   
    
    private static String[] heroDetect;
    private static String[] goblinDetect;
    
    public void initArray(){
        
        /*
        heroDetect[1]=s1.getPlayerDetectName();
        heroDetect[2]=s2.getPlayerDetectName();
        heroDetect[3]=s3.getPlayerDetectName();
        heroDetect[4]=s4.getPlayerDetectName();
        heroDetect[5]=s5.getPlayerDetectName();
        heroDetect[6]=s6.getPlayerDetectName();
        heroDetect[7]=s7.getPlayerDetectName();
        heroDetect[8]=s8.getPlayerDetectName();
        heroDetect[9]=s9.getPlayerDetectName();
        heroDetect[10]=s10.getPlayerDetectName();
        */
        
        
        /*
        goblinDetect[1]=s1.getEnemyDetectName();
        goblinDetect[2]=s2.getEnemyDetectName();
        goblinDetect[3]=s3.getEnemyDetectName();
        goblinDetect[4]=s4.getEnemyDetectName();
        goblinDetect[5]=s5.getEnemyDetectName();
        goblinDetect[6]=s6.getEnemyDetectName();
        goblinDetect[7]=s7.getEnemyDetectName();
        goblinDetect[8]=s8.getEnemyDetectName();
        goblinDetect[9]=s9.getEnemyDetectName();
        goblinDetect[10]=s10.getEnemyDetectName();
        */
    
    }

    
    /**
     * Creates new form JFrame
     */
    public MainFrame() {
        initComponents();
        
    }
    public MainFrame(String name){
        super(name);
        initComponents();
    }
    
    
    public static void openScene(int index){
        //j.add(scene[index]);
    }
    
    public static String[] getHeroDetect(){
        return heroDetect;
    }
    
    public static String[] getEnemyDetect(){
        return goblinDetect;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 400, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        
        ArrayList<JPanel> scene = new ArrayList<>();
        MainFrame j = new MainFrame("Hero wars");
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                Home home = new Home();
                scene.add(home);
                j.setSize(960, 540);
                j.setDefaultCloseOperation(MainFrame.EXIT_ON_CLOSE);
                j.setEnabled(true);
                j.setVisible(true);
                j.add(scene.get(0));
            }
        });
        
        
        
        /*
        Home home = new Home();
        Scene1 s1 = new Scene1();
        Scene2 s2 = new Scene2();
        Scene3 s3 = new Scene3();
        Scene4 s4 = new Scene4();
        Scene5 s5 = new Scene5();
        Scene6 s6 = new Scene6();
        Scene7 s7 = new Scene7();
        Scene8 s8 = new Scene8();
        Scene9 s9 = new Scene9();
        Scene10 s10 = new Scene10();
        Pause pause = new Pause();
        Result result = new Result();
        */
        
        /*
        scene[0]=home;  scene[1]=s1;    scene[2]=s2;    scene[3]=s3;
        scene[4]=s4;    scene[5]=s5;    scene[6]=s6;    scene[7]=s7;
        scene[8]=s8;    scene[9]=s9;    scene[10]=s10;
        scene[11]=pause;    scene[12]=result;
        */
        
        
        System.out.print("TEST");     //////
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
