/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goblinherowar.Frame;

import goblinherowar.API.GameManager;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author peeravich.c
 */
public class Scene3 extends Scene implements GetDetectName{

    /**
     * Creates new form Scene3
     */
    public Scene3() {
        initComponents();
        
        resetScene();
        //GameManager.setGoblinBar(s1EnemyHPBar);
        //GameManager.setPlayerBar(s1PlayerHPBar);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Scene Method">
    public String getPlayerDetectName(){
        return playerDetect.getName();
    }
    
    public String getEnemyDetectName(){
        return enemyDetect.getName();
    }
    
    public ArrayList<JButton> getButton(){
        ArrayList<JButton> b = new ArrayList<>();
        b.add(key1);
        b.add(key2);
        b.add(key3);
        b.add(key4);
        return b;
    }
    
    public void resetScene(){
        setting.setOpaque(false);
        setting.setContentAreaFilled(false);
        setting.setBorderPainted(false);
        
        key1.setEnabled(true);
        key2.setEnabled(true);
        key3.setEnabled(true);
        key4.setEnabled(true);
        key1.setVisible(true);
        key2.setVisible(true);
        key3.setVisible(true);
        key4.setVisible(true);
        /*
        key1.setLocation(,);
        key2.setLocation(,);
        key3.setLocation(,);
        key4.setLocation(,);
        */
        top1.setVisible(true);
        top2.setVisible(true);
        top3.setVisible(true);
        top4.setVisible(true);
        mid1_L.setVisible(false);
        mid2_L.setVisible(false);
        mid3_L.setVisible(false);
        mid_M.setVisible(false);
        mid1_R.setVisible(false);
        mid2_R.setVisible(false);
        mid3_R.setVisible(false);
        enemyDetect.setVisible(false);
        playerDetect.setVisible(false);
        /*
        key1cnt = key2cnt = key3cnt = 0;
        key1Open = key2Open = key3Open = false;
        
        enemyHPBar.setForeground(Color.red);
        enemyHPBar.setValue(GameManager.goblinHP);
        playerHPBar.setForeground(Color.red);
        playerHPBar.setValue(GameManager.heroHP);
        */
    }
//</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        key1 = new javax.swing.JButton();
        key2 = new javax.swing.JButton();
        key3 = new javax.swing.JButton();
        key4 = new javax.swing.JButton();
        top1 = new javax.swing.JLabel();
        top2 = new javax.swing.JLabel();
        top3 = new javax.swing.JLabel();
        top4 = new javax.swing.JLabel();
        mid1_L = new javax.swing.JLabel();
        mid2_L = new javax.swing.JLabel();
        mid3_L = new javax.swing.JLabel();
        mid1_R = new javax.swing.JLabel();
        mid2_R = new javax.swing.JLabel();
        mid3_R = new javax.swing.JLabel();
        mid_M = new javax.swing.JLabel();
        playerDetect = new javax.swing.JLabel();
        enemyDetect = new javax.swing.JLabel();
        setting = new javax.swing.JButton();
        Scene3 = new javax.swing.JLabel();

        setLayout(null);

        key1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/key1.png"))); // NOI18N
        add(key1);
        key1.setBounds(400, 80, 138, 60);

        key2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/key2.png"))); // NOI18N
        add(key2);
        key2.setBounds(430, 170, 138, 60);

        key3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/key3.png"))); // NOI18N
        add(key3);
        key3.setBounds(160, 230, 138, 60);

        key4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/key4.png"))); // NOI18N
        add(key4);
        key4.setBounds(670, 170, 70, 140);

        top1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/top1.png"))); // NOI18N
        add(top1);
        top1.setBounds(310, 10, 370, 100);

        top2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/top2.png"))); // NOI18N
        add(top2);
        top2.setBounds(310, 40, 370, 70);

        top3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/top3.png"))); // NOI18N
        add(top3);
        top3.setBounds(310, 60, 370, 50);

        top4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/top4.png"))); // NOI18N
        add(top4);
        top4.setBounds(310, 80, 370, 30);

        mid1_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/mid1_L.png"))); // NOI18N
        add(mid1_L);
        mid1_L.setBounds(350, 150, 110, 50);

        mid2_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/mid2_L.png"))); // NOI18N
        add(mid2_L);
        mid2_L.setBounds(230, 150, 130, 50);

        mid3_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/mid3_L.png"))); // NOI18N
        add(mid3_L);
        mid3_L.setBounds(230, 180, 50, 90);

        mid1_R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/mid1_R.png"))); // NOI18N
        add(mid1_R);
        mid1_R.setBounds(460, 200, 60, 100);

        mid2_R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/mid2_R.png"))); // NOI18N
        add(mid2_R);
        mid2_R.setBounds(510, 240, 100, 60);

        mid3_R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/mid3_R.png"))); // NOI18N
        add(mid3_R);
        mid3_R.setBounds(600, 240, 110, 60);

        mid_M.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/mid_M.png"))); // NOI18N
        add(mid_M);
        mid_M.setBounds(460, 110, 60, 90);

        playerDetect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/fail.png"))); // NOI18N
        add(playerDetect);
        playerDetect.setBounds(700, 240, 60, 100);

        enemyDetect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/win.png"))); // NOI18N
        add(enemyDetect);
        enemyDetect.setBounds(230, 260, 60, 100);

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/setting.png"))); // NOI18N
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });
        add(setting);
        setting.setBounds(880, 10, 67, 70);

        Scene3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene3Component/Scene3.jpg"))); // NOI18N
        Scene3.setSize(new java.awt.Dimension(960, 540));
        add(Scene3);
        Scene3.setBounds(0, 0, 960, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingActionPerformed
        // TODO add your handling code here:
        GameManager.pauseGame();
        MainFrame.addScene(11,0);
        MainFrame.setSceneVisible(11,true);
        key1.setEnabled(false);
        key2.setEnabled(false);
        key3.setEnabled(false);
        key4.setEnabled(false);
    }//GEN-LAST:event_settingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Scene3;
    private javax.swing.JLabel enemyDetect;
    private javax.swing.JButton key1;
    private javax.swing.JButton key2;
    private javax.swing.JButton key3;
    private javax.swing.JButton key4;
    private javax.swing.JLabel mid1_L;
    private javax.swing.JLabel mid1_R;
    private javax.swing.JLabel mid2_L;
    private javax.swing.JLabel mid2_R;
    private javax.swing.JLabel mid3_L;
    private javax.swing.JLabel mid3_R;
    private javax.swing.JLabel mid_M;
    private javax.swing.JLabel playerDetect;
    private javax.swing.JButton setting;
    private javax.swing.JLabel top1;
    private javax.swing.JLabel top2;
    private javax.swing.JLabel top3;
    private javax.swing.JLabel top4;
    // End of variables declaration//GEN-END:variables
}
