/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goblinherowar.Frame;

import goblinherowar.API.GameManager;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author peeravich.c
 */
public class Scene7 extends Scene implements GetDetectName{

    /**
     * Creates new form Scene7
     */
    public Scene7() {
        initComponents();
        
        resetScene();
        //GameManager.setGoblinBar(s1EnemyHPBar);
        //GameManager.setPlayerBar(s1PlayerHPBar);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Scene Method">
    public String getPlayerDetectName(){
        return playerDetect.getName();
    }
    
    public String getEnemyDetectName(){
        return enemyDetect.getName();
    }

    public ArrayList<JButton> getButton(){
        ArrayList<JButton> b = new ArrayList<>();
        b.add(key1);
        b.add(key2);
        b.add(key3);
        b.add(key4);
        b.add(key5);
        b.add(key6);
        return b;
    }
    
    public void resetScene(){
        setting.setOpaque(false);
        setting.setContentAreaFilled(false);
        setting.setBorderPainted(false);
        
        key1.setEnabled(true);
        key2.setEnabled(true);
        key3.setEnabled(true);
        key4.setEnabled(true);
        key5.setEnabled(true);
        key6.setEnabled(true);
        key1.setVisible(true);
        key2.setVisible(true);
        key3.setVisible(true);
        key4.setVisible(true);
        key5.setVisible(true);
        key6.setVisible(true);
        /*
        key1.setLocation(,);
        key2.setLocation(,);
        key3.setLocation(,);
        key4.setLocation(,);
        key5.setLocation(,);
        key6.setLocation(,);
        */
        top1_L.setVisible(true);
        top2_L.setVisible(true);
        top3_L.setVisible(true);
        top1_R.setVisible(true);
        top2_R.setVisible(true);
        top3_R.setVisible(true);
        mid1_L.setVisible(false);
        mid2_L.setVisible(false);
        mid3_L.setVisible(false);
        mid4_L.setVisible(false);
        mid1_R.setVisible(false);
        mid2_R.setVisible(false);
        mid3_R.setVisible(false);
        mid_M.setVisible(false);
        bottom1_L.setVisible(false);
        bottom2_L.setVisible(false);
        bottom3_L.setVisible(false);
        bottom4_L.setVisible(false);
        bottom1_R.setVisible(false);
        bottom2_R.setVisible(false);
        enemyDetect.setVisible(false);
        playerDetect.setVisible(false);
        /*
        key1cnt = key2cnt = key3cnt = 0;
        key1Open = key2Open = key3Open = false;
        
        enemyHPBar.setForeground(Color.red);
        enemyHPBar.setValue(GameManager.goblinHP);
        playerHPBar.setForeground(Color.red);
        playerHPBar.setValue(GameManager.heroHP);
        */
    }
//</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        key1 = new javax.swing.JButton();
        key2 = new javax.swing.JButton();
        key3 = new javax.swing.JButton();
        key4 = new javax.swing.JButton();
        key5 = new javax.swing.JButton();
        key6 = new javax.swing.JButton();
        top1_L = new javax.swing.JLabel();
        top2_L = new javax.swing.JLabel();
        top3_L = new javax.swing.JLabel();
        top1_R = new javax.swing.JLabel();
        top2_R = new javax.swing.JLabel();
        top3_R = new javax.swing.JLabel();
        mid1_L = new javax.swing.JLabel();
        mid2_L = new javax.swing.JLabel();
        mid3_L = new javax.swing.JLabel();
        mid4_L = new javax.swing.JLabel();
        mid1_R = new javax.swing.JLabel();
        mid2_R = new javax.swing.JLabel();
        mid3_R = new javax.swing.JLabel();
        mid_M = new javax.swing.JLabel();
        bottom1_L = new javax.swing.JLabel();
        bottom2_L = new javax.swing.JLabel();
        bottom3_L = new javax.swing.JLabel();
        bottom4_L = new javax.swing.JLabel();
        bottom1_R = new javax.swing.JLabel();
        bottom2_R = new javax.swing.JLabel();
        playerDetect = new javax.swing.JLabel();
        enemyDetect = new javax.swing.JLabel();
        setting = new javax.swing.JButton();
        Scene7 = new javax.swing.JLabel();

        setLayout(null);

        key1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/key1.png"))); // NOI18N
        add(key1);
        key1.setBounds(110, 90, 126, 60);

        key2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/key2.png"))); // NOI18N
        add(key2);
        key2.setBounds(480, 100, 55, 140);

        key3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/key3.png"))); // NOI18N
        add(key3);
        key3.setBounds(110, 180, 126, 60);

        key4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/key4.png"))); // NOI18N
        add(key4);
        key4.setBounds(680, 180, 126, 60);

        key5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/key5.png"))); // NOI18N
        add(key5);
        key5.setBounds(240, 270, 126, 60);

        key6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/key6.png"))); // NOI18N
        add(key6);
        key6.setBounds(720, 270, 126, 60);

        top1_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/top1_L.png"))); // NOI18N
        add(top1_L);
        top1_L.setBounds(130, 40, 110, 80);

        top2_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/top2_L.png"))); // NOI18N
        add(top2_L);
        top2_L.setBounds(130, 70, 110, 50);

        top3_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/top3_L.png"))); // NOI18N
        add(top3_L);
        top3_L.setBounds(130, 90, 110, 30);

        top1_R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/top1_R.png"))); // NOI18N
        add(top1_R);
        top1_R.setBounds(670, 40, 110, 80);

        top2_R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/top2_R.png"))); // NOI18N
        add(top2_R);
        top2_R.setBounds(670, 70, 110, 50);

        top3_R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/top3_R.png"))); // NOI18N
        add(top3_R);
        top3_R.setBounds(670, 90, 110, 30);

        mid1_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/mid1_L.png"))); // NOI18N
        add(mid1_L);
        mid1_L.setBounds(180, 120, 30, 94);

        mid2_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/mid2_L.png"))); // NOI18N
        add(mid2_L);
        mid2_L.setBounds(180, 170, 110, 40);

        mid3_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/mid3_L.png"))); // NOI18N
        add(mid3_L);
        mid3_L.setBounds(280, 170, 110, 40);

        mid4_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/mid4_L.png"))); // NOI18N
        add(mid4_L);
        mid4_L.setBounds(380, 170, 90, 40);

        mid1_R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/mid1_R.png"))); // NOI18N
        add(mid1_R);
        mid1_R.setBounds(710, 120, 33, 90);

        mid2_R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/mid2_R.png"))); // NOI18N
        add(mid2_R);
        mid2_R.setBounds(610, 170, 120, 40);

        mid3_R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/mid3_R.png"))); // NOI18N
        add(mid3_R);
        mid3_R.setBounds(500, 170, 120, 40);

        mid_M.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/mid1_M.png"))); // NOI18N
        add(mid_M);
        mid_M.setBounds(470, 170, 40, 90);

        bottom1_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/bottom1_L.png"))); // NOI18N
        add(bottom1_L);
        bottom1_L.setBounds(180, 210, 30, 50);

        bottom2_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/bottom2_L.png"))); // NOI18N
        add(bottom2_L);
        bottom2_L.setBounds(180, 260, 90, 30);

        bottom3_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/bottom3_L.png"))); // NOI18N
        add(bottom3_L);
        bottom3_L.setBounds(260, 260, 110, 30);

        bottom4_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/bottom4_L.png"))); // NOI18N
        add(bottom4_L);
        bottom4_L.setBounds(370, 250, 140, 50);

        bottom1_R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/bottom1_R.png"))); // NOI18N
        add(bottom1_R);
        bottom1_R.setBounds(710, 210, 40, 80);

        bottom2_R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/bottom2_R.png"))); // NOI18N
        add(bottom2_R);
        bottom2_R.setBounds(740, 260, 70, 40);

        playerDetect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/fail.png"))); // NOI18N
        add(playerDetect);
        playerDetect.setBounds(750, 300, 60, 90);

        enemyDetect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/win.png"))); // NOI18N
        add(enemyDetect);
        enemyDetect.setBounds(280, 300, 56, 90);

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/setting.png"))); // NOI18N
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });
        add(setting);
        setting.setBounds(880, 10, 67, 70);

        Scene7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene7Component/Scene7.jpg"))); // NOI18N
        Scene7.setSize(new java.awt.Dimension(960, 540));
        add(Scene7);
        Scene7.setBounds(0, 0, 960, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingActionPerformed
        // TODO add your handling code here:
        GameManager.pauseGame();
        MainFrame.addScene(11,0);
        MainFrame.setSceneVisible(11,true);
        key1.setEnabled(false);
        key2.setEnabled(false);
        key3.setEnabled(false);
        key4.setEnabled(false);
        key5.setEnabled(false);
        key6.setEnabled(false);
    }//GEN-LAST:event_settingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Scene7;
    private javax.swing.JLabel bottom1_L;
    private javax.swing.JLabel bottom1_R;
    private javax.swing.JLabel bottom2_L;
    private javax.swing.JLabel bottom2_R;
    private javax.swing.JLabel bottom3_L;
    private javax.swing.JLabel bottom4_L;
    private javax.swing.JLabel enemyDetect;
    private javax.swing.JButton key1;
    private javax.swing.JButton key2;
    private javax.swing.JButton key3;
    private javax.swing.JButton key4;
    private javax.swing.JButton key5;
    private javax.swing.JButton key6;
    private javax.swing.JLabel mid1_L;
    private javax.swing.JLabel mid1_R;
    private javax.swing.JLabel mid2_L;
    private javax.swing.JLabel mid2_R;
    private javax.swing.JLabel mid3_L;
    private javax.swing.JLabel mid3_R;
    private javax.swing.JLabel mid4_L;
    private javax.swing.JLabel mid_M;
    private javax.swing.JLabel playerDetect;
    private javax.swing.JButton setting;
    private javax.swing.JLabel top1_L;
    private javax.swing.JLabel top1_R;
    private javax.swing.JLabel top2_L;
    private javax.swing.JLabel top2_R;
    private javax.swing.JLabel top3_L;
    private javax.swing.JLabel top3_R;
    // End of variables declaration//GEN-END:variables
}
