/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goblinherowar.Frame;

import goblinherowar.API.GameManager;
import goblinherowar.API.Util;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.Timer;

/**
 *
 * @author peeravich.c
 */
public class Scene2 extends Scene implements GetDetectName{
    // <editor-fold defaultstate="collapsed" desc="Instance variable">
    private int key1cnt = 0;
    private int key2cnt = 0;
    private int key3cnt = 0;
    private int key4cnt = 0;
    private boolean key1Open = false;
    private boolean key2Open = false;
    private boolean key3Open = false;
    private boolean key4Open = false;
    private Timer[] t = new Timer[10];
    private int[] timeCounter = new int[10];
    private int idx = 0;
    private int key1Interrupt,key2Interrupt,key3Interrupt,key4Interrupt;
    //</editor-fold>
    

    /**
     * Creates new form Scene2
     */
    public Scene2() {
        initComponents();
        
        resetScene();
        GameManager.setGoblinBar(enemyHPBar);
        GameManager.setPlayerBar(playerHPBar);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Scene Method">
    public String getPlayerDetectName(){
        return playerDetect.getName();
    }
    
    public String getEnemyDetectName(){
        return enemyDetect.getName();
    }
    
    public ArrayList<JButton> getButton(){
        ArrayList<JButton> b = new ArrayList<>();
        b.add(key1);
        b.add(key2);
        b.add(key3);
        b.add(key4);
        return b;
    }
    
    public void resetScene(){
        setting.setOpaque(false);
        setting.setContentAreaFilled(false);
        setting.setBorderPainted(false);
        
        key1.setEnabled(true);
        key2.setEnabled(true);
        key3.setEnabled(true);
        key4.setEnabled(true);
        key1.setVisible(true);
        key2.setVisible(true);
        key3.setVisible(true);
        key4.setVisible(true);
        Util.moveButton(key1, key1.getX(), key1.getY());
        Util.moveButton(key2, key2.getX(), key2.getY());
        Util.moveButton(key3, key3.getX(), key3.getY());
        Util.moveButton(key4, key4.getX(), key4.getY());
        
        top1.setVisible(true);
        top2.setVisible(true);
        top3.setVisible(true);
        top4.setVisible(true);
        mid1_L.setVisible(false);
        mid2_L.setVisible(false);
        mid3_L.setVisible(false);
        mid1_R.setVisible(false);
        mid2_R.setVisible(false);
        mid3_R.setVisible(false);
        bottom1_L.setVisible(false);
        bottom2_L.setVisible(false);
        bottom_M.setVisible(false);
        bottom1_R.setVisible(false);
        bottom2_R.setVisible(false);
        enemyDetect.setVisible(false);
        playerDetect.setVisible(false);
        
        key1cnt = key2cnt = key3cnt = key4cnt = 0;
        key1Open = key2Open = key3Open = key4Open = false;
        key1Interrupt = key2Interrupt = key3Interrupt = key4Interrupt = -1;
        
        enemyHPBar.setForeground(Color.red);
        enemyHPBar.setValue(GameManager.goblinHP);
        playerHPBar.setForeground(Color.red);
        playerHPBar.setValue(GameManager.heroHP);
    }
//</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        key1 = new javax.swing.JButton();
        key2 = new javax.swing.JButton();
        key3 = new javax.swing.JButton();
        key4 = new javax.swing.JButton();
        top1 = new javax.swing.JLabel();
        top2 = new javax.swing.JLabel();
        top3 = new javax.swing.JLabel();
        top4 = new javax.swing.JLabel();
        mid1_L = new javax.swing.JLabel();
        mid2_L = new javax.swing.JLabel();
        mid3_L = new javax.swing.JLabel();
        mid1_R = new javax.swing.JLabel();
        mid2_R = new javax.swing.JLabel();
        mid3_R = new javax.swing.JLabel();
        bottom1_L = new javax.swing.JLabel();
        bottom2_L = new javax.swing.JLabel();
        bottom_M = new javax.swing.JLabel();
        bottom1_R = new javax.swing.JLabel();
        bottom2_R = new javax.swing.JLabel();
        playerDetect = new javax.swing.JLabel();
        enemyDetect = new javax.swing.JLabel();
        setting = new javax.swing.JButton();
        playerHPBar = new javax.swing.JProgressBar();
        enemyHPBar = new javax.swing.JProgressBar();
        Scene2 = new javax.swing.JLabel();

        setLayout(null);

        key1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/key1.png"))); // NOI18N
        key1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key1ActionPerformed(evt);
            }
        });
        add(key1);
        key1.setBounds(270, 40, 70, 140);

        key2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/key2.png"))); // NOI18N
        key2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key2ActionPerformed(evt);
            }
        });
        add(key2);
        key2.setBounds(640, 40, 70, 140);

        key3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/key3.png"))); // NOI18N
        key3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key3ActionPerformed(evt);
            }
        });
        add(key3);
        key3.setBounds(150, 210, 140, 70);

        key4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/key4.png"))); // NOI18N
        key4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key4ActionPerformed(evt);
            }
        });
        add(key4);
        key4.setBounds(680, 210, 140, 70);

        top1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/top1.png"))); // NOI18N
        add(top1);
        top1.setBounds(310, 10, 360, 140);

        top2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/top2.png"))); // NOI18N
        add(top2);
        top2.setBounds(310, 40, 370, 110);

        top3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/top3.png"))); // NOI18N
        add(top3);
        top3.setBounds(310, 80, 370, 70);

        top4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/top4.png"))); // NOI18N
        add(top4);
        top4.setBounds(310, 110, 370, 40);

        mid1_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/mid1_L.png"))); // NOI18N
        add(mid1_L);
        mid1_L.setBounds(210, 100, 100, 60);

        mid2_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/mid2_L.png"))); // NOI18N
        add(mid2_L);
        mid2_L.setBounds(210, 140, 50, 70);

        mid3_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/mid3_L.png"))); // NOI18N
        add(mid3_L);
        mid3_L.setBounds(210, 200, 50, 50);

        mid1_R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/mid1_R.png"))); // NOI18N
        add(mid1_R);
        mid1_R.setBounds(670, 110, 90, 40);

        mid2_R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/mid2_R.png"))); // NOI18N
        add(mid2_R);
        mid2_R.setBounds(710, 140, 50, 70);

        mid3_R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/mid3_R.png"))); // NOI18N
        add(mid3_R);
        mid3_R.setBounds(710, 200, 50, 50);

        bottom1_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/bottom1_L.png"))); // NOI18N
        add(bottom1_L);
        bottom1_L.setBounds(250, 200, 110, 50);

        bottom2_L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/bottom2_L.png"))); // NOI18N
        add(bottom2_L);
        bottom2_L.setBounds(340, 200, 110, 50);

        bottom_M.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/bottom_M.png"))); // NOI18N
        add(bottom_M);
        bottom_M.setBounds(430, 200, 110, 50);

        bottom1_R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/bottom1_R.png"))); // NOI18N
        add(bottom1_R);
        bottom1_R.setBounds(620, 200, 110, 50);

        bottom2_R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/bottom2_R.png"))); // NOI18N
        add(bottom2_R);
        bottom2_R.setBounds(530, 200, 110, 50);

        playerDetect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/fail.png"))); // NOI18N
        add(playerDetect);
        playerDetect.setBounds(710, 240, 40, 90);

        enemyDetect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/win.png"))); // NOI18N
        add(enemyDetect);
        enemyDetect.setBounds(210, 240, 50, 100);

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/setting.png"))); // NOI18N
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });
        add(setting);
        setting.setBounds(880, 10, 67, 70);
        add(playerHPBar);
        playerHPBar.setBounds(670, 500, 120, 30);
        add(enemyHPBar);
        enemyHPBar.setBounds(170, 500, 120, 30);

        Scene2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goblinherowar/Frame/Component/scene2Component/Scene2.jpg"))); // NOI18N
        Scene2.setSize(new java.awt.Dimension(960, 540));
        add(Scene2);
        Scene2.setBounds(0, 0, 960, 540);
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Setting Performed">
    private void settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingActionPerformed
        // TODO add your handling code here:
        GameManager.pauseGame();
        MainFrame.addScene(11,0);
        MainFrame.setSceneVisible(11,true);
        key1.setEnabled(false);
        key2.setEnabled(false);
        key3.setEnabled(false);
        key4.setEnabled(false);
    }//GEN-LAST:event_settingActionPerformed
// </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Key1 Performed">
    private void key1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key1ActionPerformed
        // TODO add your handling code here:
        if(!key1.isEnabled()) return;
        key1Open = !key1Open;
        key1cnt++;
        // <editor-fold defaultstate="collapsed" desc="open key"> 
        if(key1cnt%2==1) {
            Util.moveButton(key1,key1.getX(),key1.getY()-40);
            recheckTimerIdx();
            timeCounter[idx] = 0;
            t[idx] = new Timer(1000, new ActionListener() {
                //@override
                public void actionPerformed(ActionEvent e) {
                    if(timeCounter[idx]<=7) key1OpenPerformed(timeCounter[idx]);
                    else if(timeCounter[idx] > 7){
                        if(!key1Open) { key1Interrupt = idx;  t[idx].stop(); return; }
                        if(key1Interrupt != -1) {  idx = key1Interrupt; key1Interrupt = -1; }
                    }
                    timeCounter[idx]++;
                }
            });
            t[idx].start();
        }
        //</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="close key"> 
        if(key1cnt%2 == 0){
            Util.moveButton(key1, key1.getX(), key1.getY()+40);
            
        }
        //</editor-fold>
        key1Open = !key1Open;
    }//GEN-LAST:event_key1ActionPerformed

    private void key1OpenPerformed(int timerCounter){
        if(timerCounter == 0 && top4.isVisible()) {
            t[idx].start();
            top1.setVisible(false);
            mid1_L.setVisible(true);
        }
        if(timerCounter == 1 && top4.isVisible()){
            t[idx].start();
            top2.setVisible(false);
            mid2_L.setVisible(true);
        }
        if (timerCounter == 2 && top4.isVisible()){
            t[idx].start();
            top3.setVisible(false);
            mid3_L.setVisible(true);
        }
        if(timerCounter == 3 && top4.isVisible()){
            t[idx].start();
            top4.setVisible(false);
            bottom1_L.setVisible(true);
            if(key3Open) { t[idx].stop();  }
        }
        if(timerCounter == 4 && mid1_L.isVisible()){
            t[idx].start();
            mid1_L.setVisible(false);
            bottom2_L.setVisible(true);
            if(key3Open) { t[idx].stop();  }
        }
        if(timerCounter == 5 && mid2_L.isVisible()){
            t[idx].start();
            mid2_L.setVisible(false);
            bottom_M.setVisible(true);
            if(key3Open) { t[idx].stop();  }
        }
        if(timerCounter == 6){
            t[idx].start();
            bottom2_R.setVisible(true);
            if(key3Open) { t[idx].stop();  }
        }
        if(timerCounter == 7){
            t[idx].start();
            bottom1_R.setVisible(true);
            mid3_R.setVisible(true);
            if(key3Open || key4Open) { t[idx].stop(); timeCounter[idx] = 0; }
        }
    }
    //</editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Key2 Performed">
    private void key2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key2ActionPerformed
        // TODO add your handling code here:
        if(!key2.isEnabled()) return;
        key2Open = !key2Open;
        key2cnt++;
        // <editor-fold defaultstate="collapsed" desc="open key"> 
        if(key2cnt%2==1) {
            Util.moveButton(key2,key2.getX(),key2.getY()-40);
            recheckTimerIdx();
            timeCounter[idx] = 0;
            t[idx] = new Timer(1000, new ActionListener() {
                //@override
                public void actionPerformed(ActionEvent e) {
                    if(timeCounter[idx]<=7) key2OpenPerformed(timeCounter[idx]);
                    else if(timeCounter[idx] > 7){
                        if(!key2Open) { key2Interrupt = idx;  t[idx].stop(); return; }
                        if(key2Interrupt != -1) {  idx = key2Interrupt; key2Interrupt = -1; }
                    }
                    timeCounter[idx]++;
                }
            });
            t[idx].start();
        }
        //</editor-fold>
        // <editor-fold defaultstate="collapsed" desc="close key"> 
        if(key2cnt%2 == 0){
            Util.moveButton(key2, key2.getX(), key2.getY()+40);
            
        }
        //</editor-fold>
        key2Open = !key2Open;
    }//GEN-LAST:event_key2ActionPerformed

    private void key2OpenPerformed(int timerCounter){
        if(timerCounter == 0 && top4.isVisible()) {
            t[idx].start();
            top1.setVisible(false);
            mid1_R.setVisible(true);
        }
        if(timerCounter == 1 && top4.isVisible()){
            t[idx].start();
            top2.setVisible(false);
            mid2_R.setVisible(true);
        }
        if (timerCounter == 2 && top4.isVisible()){
            t[idx].start();
            top3.setVisible(false);
            mid3_R.setVisible(true);
        }
        if(timerCounter == 3 && top4.isVisible()){
            t[idx].start();
            top4.setVisible(false);
            bottom1_R.setVisible(true);
            if(key4Open) { t[idx].stop();  }
        }
        if(timerCounter == 4 && mid1_R.isVisible()){
            t[idx].start();
            mid1_R.setVisible(false);
            bottom2_R.setVisible(true);
            if(key4Open) { t[idx].stop();  }
        }
        if(timerCounter == 5 && mid2_R.isVisible()){
            t[idx].start();
            mid2_L.setVisible(false);
            bottom_M.setVisible(true);
            if(key4Open) { t[idx].stop(); }
        }
        if(timerCounter == 6){
            t[idx].start();
            bottom2_L.setVisible(true);
            if(key4Open) { t[idx].stop();  }
        }
        if(timerCounter == 7){
            t[idx].start();
            bottom1_L.setVisible(true);
            mid3_L.setVisible(true);
            if(key3Open || key4Open) { t[idx].stop(); timeCounter[idx] = 0; }
        }
    }
    //</editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Key3 Performed">
    private void key3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key3ActionPerformed
        // TODO add your handling code here:
        if(!key3.isEnabled()) return;
        key3Open = !key3Open;
        key3cnt++;
        
        if(key3cnt%2 == 1) Util.moveButton(key3, key3.getX()-80, key3.getY());
        else Util.moveButton(key3, key3.getX()+80, key3.getY());
        
        if(!key3Open && !mid3_L.isVisible()) return;
        if(!key3.isEnabled()) return;
        if(mid3_L.isVisible()){ 
            if(key3cnt%2==1){
                enemyDetect.setVisible(true);
                GameManager.goblinDamaged();
            }
            else{
                enemyDetect.setVisible(false);
                GameManager.stopGoblinDamage();
            }
        }
    }//GEN-LAST:event_key3ActionPerformed
//</editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Key4 Performed">
    private void key4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key4ActionPerformed
        // TODO add your handling code here:
        if(!key4.isEnabled()) return;
        key4Open = !key4Open;
        key4cnt++;
        
        if(key4cnt%2 == 1) Util.moveButton(key4, key4.getX()+80, key4.getY());
        else Util.moveButton(key4, key4.getX()-80, key4.getY());
        
        if(!key4Open && !mid3_R.isVisible()) return;
        if(!key4.isEnabled()) return;
        if(mid3_R.isVisible()){ 
            if(key4cnt%2==1){
                playerDetect.setVisible(true);
                GameManager.playerDamaged();
            }
            else{
                playerDetect.setVisible(false);
                GameManager.stopHeroDamaged();
            }
        }
        
    }//GEN-LAST:event_key4ActionPerformed
//</editor-fold>
    
    private void recheckTimerIdx(){
        if (idx == timeCounter.length-1) idx = 0;
        else idx+=1;
    }

    // <editor-fold defaultstate="collapsed" desc="Generate Variable">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Scene2;
    private javax.swing.JLabel bottom1_L;
    private javax.swing.JLabel bottom1_R;
    private javax.swing.JLabel bottom2_L;
    private javax.swing.JLabel bottom2_R;
    private javax.swing.JLabel bottom_M;
    private javax.swing.JLabel enemyDetect;
    private javax.swing.JProgressBar enemyHPBar;
    private javax.swing.JButton key1;
    private javax.swing.JButton key2;
    private javax.swing.JButton key3;
    private javax.swing.JButton key4;
    private javax.swing.JLabel mid1_L;
    private javax.swing.JLabel mid1_R;
    private javax.swing.JLabel mid2_L;
    private javax.swing.JLabel mid2_R;
    private javax.swing.JLabel mid3_L;
    private javax.swing.JLabel mid3_R;
    private javax.swing.JLabel playerDetect;
    private javax.swing.JProgressBar playerHPBar;
    private javax.swing.JButton setting;
    private javax.swing.JLabel top1;
    private javax.swing.JLabel top2;
    private javax.swing.JLabel top3;
    private javax.swing.JLabel top4;
    // End of variables declaration//GEN-END:variables
}
//</editor-fold>